export const SPELLS = [
  {
    id: "poison_stream",
    name: "Poison Stream",
    type: "combat",
    timing: "combat",
    oncePerBattle: true,
    recharge: 50,
    targetMode: "multiEnemyDistinct",
    targetCount: 2,
    steps: [
      { type: "attackFixed", fighting: 5, times: 2, mustBeDifferentTargets: true },
    ],
  },
  {
    id: "unfailing_strike",
    name: "Unfailing Strike",
    type: "combat",
    timing: "combat",
    oncePerBattle: true,
    recharge: 50,
    targetMode: "singleEnemy",
    steps: [
      { type: "damageFixed", amount: 3, bypassDefence: true },
    ],
  },
  {
    id: "armour_of_heaven",
    name: "Armour of Heaven",
    type: "combat",
    timing: "combat",
    oncePerBattle: true,
    recharge: 50,
    targetMode: "singleAlly",
    steps: [
      { type: "buffArmour", amount: 3, duration: "battle" },
    ],
  },
  {
    id: "ice_bolt",
    name: "Ice Bolt",
    type: "combat",
    timing: "combat",
    oncePerBattle: true,
    recharge: 50,
    targetMode: "singleEnemy",
    steps: [
      { type: "attackFixed", fighting: 8, times: 1 },
    ],
  },
  {
    id: "soothing_touch",
    name: "Soothing Touch",
    type: "combat",
    timing: "combatOrAdventure",
    oncePerBattle: true,
    recharge: 50,
    targetMode: "singleAlly",
    steps: [
      { type: "healFixed", amount: 5 },
    ],
  },
  {
    id: "sandstorm",
    name: "Sandstorm",
    type: "combat",
    timing: "combat",
    oncePerBattle: true,
    recharge: 50,
    targetMode: "allEnemies",
    steps: [
      { type: "attackEachEnemy", fighting: 3 },
    ],
  },
  {
    id: "clinging_dread",
    name: "Clinging Dread",
    type: "mass_combat",
    timing: "mass_combat",
    oncePerBattle: false,
    recharge: 50,
    targetMode: "singleEnemyUnit",
    steps: [
      { type: "massReduceMorale", amount: 1 },
    ],
    description: "Reduce the Morale score of an enemy unit by 1 point.",
  },
  {
    id: "animal_speech",
    name: "Animal Speech",
    type: "adventure",
    timing: "adventure",
    recharge: 50,
    description: "You are able to communicate using the secret language of animals.",
    targetMode: null,
    steps: [],
  },
  {
    id: "wolf_spirit",
    name: "Wolf Spirit",
    type: "adventure",
    timing: "adventure",
    recharge: 75,
    description: "Cast this spell when you fail a Survival check. You gain an additional 3 automatic successes for this check only.",
    targetMode: null,
    steps: [],
  },
  {
    id: "magic_cabinet",
    name: "Magic Cabinet",
    type: "adventure",
    timing: "adventure",
    recharge: 100,
    description: "You summon a magic cabinet made of purple wood. You can use this cabinet to access The Vault, storing and/or taking out as many items as you wish.",
    targetMode: null,
    steps: [],
  },
];

export function getSpellById(id) {
  return SPELLS.find(s => s.id === id) || null;
}
